### PR TITLE
#256 : cairo version support for 2.7.0

### PR DESCRIPTION
**Pull request by pravo23**

### CODE REVIEW

**Review by taco-paco — CHANGES_REQUESTED** [review]
Thanks for the PR. 
You also need to run script and commit new submodule.

@varex83 do we need to upgrade scarb as well for this?

**Comment by varex83** [comment]
> Thanks for the PR. You also need to run script and commit new submodule.
> 
> @varex83 do we need to upgrade scarb as well for this?

For now, the latest version of Scarb is 2.6.5, so I think no

**Comment by pravo23** [comment]
I have pushed the change. Please check.

**Review by varex83 — APPROVED** [review]
GTG

**Pull request merged**
