### PR TITLE
save compiled contracts to localStorage

### PR DESCRIPTION
**Pull request by kwkr**
Add saving compiled contract to be able to resume a development session. #178

### CODE REVIEW

**Comment by kwkr** [comment]
A few things that I have noticed (I'm just a beginner when it comes to StarkNet so this can also be my lack of knowledge):
- when deploying a contract, it's possible to deploy it multiple times which causes `deployedInfo` to be populated with duplicated data.
- the form is not allowing/makes it hard to deploy contracts without a constructor. There is always a field `value_` that causes the deployment to fail. Is this expected behavior?

**Comment by rjnrohit** [comment]
> A few things that I have noticed (I'm just a beginner when it comes to StarkNet so this can also be my lack of knowledge):
> 
> * when deploying a contract, it's possible to deploy it multiple times which causes `deployedInfo` to be populated with duplicated data.
> * the form is not allowing/makes it hard to deploy contracts without a constructor. There is always a field `value_` that causes the deployment to fail. Is this expected behavior?

Are you talking about this : https://github.com/NethermindEth/starknet-remix-plugin/blob/f18d1e9441e84cff54e39f70d07937c369ed6c6d/plugin/src/features/Deployment/index.tsx#L455 which is causing duplication? If yes then yeah, there is a duplication there, you can modify the code to store unique pairs

I just deployed this contract: https://codeshare.io/r49mXY and I'm able to deploy it successfully , if you are getting some error for your contract then please paste the errors here

**Comment by rjnrohit** [comment]
I see the problem, would you able to add a fix for this ? Thanks for pointing it out @kwkr

**Comment by kwkr** [comment]
@rjnrohit , I think the problem lies within the library that is used for rendering the constructor `starknet-abi-form`. It seems like the form state is somehow hidden in a global state and once it's activated, it couldn't reset it from the plugin level. There seems to be some `jotai` atom there that is holding the value (there is some field with generic name `constructor`. I tried different ways to change the state by passing different abi arrays (to refresh the props) but it doesn't work. So I assume the problem is somewhere there.

**Comment by rjnrohit** [comment]
@kwkr If you want then you contribute to this repo:https://github.com/NethermindEth/starknet-abi-form as well , you can submit a PR there as well

**Comment by kwkr** [comment]
@rjnrohit , okay, will do it in a separate issue then since it doesn't seem to be directly connected to this one.

**Comment by rjnrohit** [comment]
Did you check the form behaviour ?

**Comment by kwkr** [comment]
@rjnrohit The form behaviour is independent of the changes in this PR. It currently exists in the official plugin version available through remix ide marketplace directly. To fix this, the `starknet-abi-from` would need to be released and then bumped here.

**Comment by rjnrohit** [comment]
New version of starknet-abi-form has been published, would you able to check it now?

**Comment by kwkr** [comment]
Thanks @rjnrohit ! I just pushed the update that prevents constructors from becoming stale.

**Comment by rjnrohit** [comment]
https://github.com/NethermindEth/starknet-remix-plugin/assets/47271616/dc684821-434f-42cd-a584-da70468fd099

It's not behaving as expected !

**Review by rjnrohit — APPROVED** [review]

**Comment by rjnrohit** [comment]
Congratulations, @kwkr! Your PR successfully made it through. 🎉🙏 Keep up the great work and continue contributing! Your efforts are truly valued

**Pull request merged**
